spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lab1?useSSL=false
    username: root
    password: Thunderhead1@



#JPA Settings
  jpa.hibernate.ddl_auto: update







management:
  endpoints:
    web:
      exposure:
        include: "health, beans, metrics"
      base-path: "/management-dashboard"
  endpoint:
    health:
      show-details: always

dummyService:
  port: 8081
  address: 127.0.0.1